name: Android CI

on:
  push:
    branches: [ "ci/cd", "main" ]
  pull_request:
    branches: [ "ci/cd" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Ionic app
        run: npm run build
      
      - name: Sync Capacitor
        run: npx cap sync android
      
      - name: Make gradlew executable
        run: chmod +x android/gradlew
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
      
      - name: Build Android app
        run: cd android && ./gradlew assemble